### ISSUE TITLE
Segregate orphans

### ISSUE THREAD

**Issue by treeowl** [AshleyYakeley/countable#3]
Exporting orphan instances of standard/well known classes means that people will think thrice about actually using this package in a project. Orphan instances should really be opt-in, topically with one instance (or a few closely-related instances) per module.

**Comment by AshleyYakeley** [comment]
Done.

**Comment by treeowl** [comment]
I think there's been a misunderstanding. `Searchable` and `Countable` instances (and whatever else) are native to the package and not orphans. Things like `Eq (a -> b)` are the problematic ones.

**Comment by AshleyYakeley** [comment]
`Eq` is a superclass of `Countable`. Therefore, I cannot expose `Countable (a -> b)`, etc, without exposing orphan instances.

**Comment by treeowl** [comment]
Oh, I see. Too bad, but unavoidable
